#: kivy 2.2.1


<MyBoxLayout>:
    orientation: 'vertical'
    Button:
        text: "Click One"
        background_color: 1, 0, 1, 1
        font_size:20
    
    Button:
        text: "Click Two"
        background_color:0,1,1,1
        font_size:20
    
    Button:
        text: "Click Three"
        background_color:1,1,0,1
        font_size:20

    Button:
        text: "Click Four"
        background_color:1,1,1,0
        font_size:20