#: kivy 2.2.1

<Button>:


<MyGridLayout>:
    cols: 2
    spacing: 10

    Button:
        text: "Click One"
        size_hint_x: None
        background_color: 0,1,1,1
        width: 50

    Button:
        text: "Click Two"
        background_color: 1,0,1,1

    Button:
        text: "Click Three"
        size_hint_x: None
        background_color: 1,1,0,1
        width: 50

    Button:
        text: "Click Four"
        background_color: 1,1,1,0.265