#: kivy 2.2.1

<MyStackLayout>:
    orientation: 'lr-tb'
    padding: 10

    Button:
        text: "Click One"
        size_hint: [.6,.2]
        background_color: 0,1,1,1

    Button:
        text: "Click Two"
        size_hint: [.4,.4]
        background_color: 1,0,1,1

    Button:
        text: "Click Three"
        size_hint: [.3,.2]
        background_color: 1,1,0,1

    Button:
        text: "Click Four"
        size_hint: [.4,.3]
        background_color: 1,1,1,1